# Generated by Django 5.2.18 on 2026-10-08 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.CharField(default='catalogo/img/default.jpg', max_length=255),
        ),
    ]
